[2025-10-08T14:53:04.247+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: Airflow_depi.print_date scheduled__2025-10-01T00:05:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
